import DS from 'ember-data';

export default DS.Model.extend({
  nova_id: DS.attr('string'),
  floating_ip: DS.attr('string'),
  vnc_url: DS.attr('string'),
  thumb: DS.attr('string'),
  created_at: DS.attr('date'),
  name: DS.attr('string'),
  topic: DS.attr('string'),
  status: DS.attr('number'),
  is_auth: DS.attr('boolean'),
  htlogin: DS.attr('string'),
  htpassword: DS.attr('string'),
  termpassword: DS.attr('string'),
  layout: DS.attr('string'),
  is_prod: DS.attr('boolean'),
  is_cached: DS.attr('boolean'),
  is_ht: DS.attr('boolean'),
  is_ci: DS.attr('boolean'),
  is_backup: DS.attr('boolean'),
  is_cors: DS.attr('boolean'),
  is_ro: DS.attr('boolean'),
  is_jenkins: DS.attr('boolean'),
  is_offline: DS.attr('boolean'),
  technos: DS.hasMany('techno'),
  uris: DS.hasMany('uri'),
  commit: DS.belongsTo('commit'),
  project: DS.belongsTo('project'),
  user: DS.belongsTo('user'),
  systemimage: DS.belongsTo('systemimage'),
  vmsize: DS.belongsTo('vmsize'),
  supervises: DS.hasMany('supervise')
});
